sudo: false
language: node_js
cache:
  directories:
    - $HOME/.cache/yarn
notifications:
  email: false
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/node_modules/slimerjs/src:$PATH
addons:
  firefox: "50.0"
node_js:
  - '6'
before_install:
#   Fail fast if ci is triggered by ci commit
  - export TALEND_COMMIT_MSG=$TRAVIS_COMMIT_MESSAGE
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export TALEND_COMMIT_MSG="$(git log --format=%B -n 1 $TRAVIS_PULL_REQUEST_SHA)"; fi
  - if [[ "$TALEND_COMMIT_MSG" =~ 'test(ci)' ]]; then travis_terminate 0; fi
#   Configure git
  - .travis/before_install.sh
before_script:
  - sh -e /etc/init.d/xvfb start
  - yarn global add sassdoc http-server surge
script:
  - yarn test:cov
after_success:
  - .travis/after_success_static.sh
  - .travis/after_success_demo.sh
  - .travis/after_success_coverage.sh
  - .travis/after_success_deploy.sh
  - .travis/after_success_lint.sh
  - .travis/after_success_screenshots.sh
  - .travis/after_success_git.sh
branches:
  only:
    - master
