language: node_js
cache:
  directories:
    - $HOME/.cache
    - $HOME/.yarn-cache
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '6'
before_install:
  npm install -g yarn
install:
  - yarn
after_success:
  - npm run test:cov
  - cat ./coverage/lcov.info | node_modules/.bin/codacy-coverage
  - rm -rf ./coverage
  - /bin/bash .travis/after_success.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
