language: node_js
cache:
  directories:
    - $HOME/.cache/yarn
notifications:
  email: false
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/node_modules/slimerjs/src:$PATH
addons:
  firefox: "50.0"
node_js:
  - '6'
before_install:
  - echo $TRAVIS_COMMIT_MESSAGE
  - 'if [ test $TRAVIS_COMMIT_MESSAGE =~ "test(ci)*" ]; then exit 0; else .travis/before_install.sh fi'
  - .travis/before_install.sh
before_script:
  - sh -e /etc/init.d/xvfb start
  - yarn global add sassdoc http-server surge
sudo: required
script:
  - yarn test
after_success:
  - .travis/after_success_lint.sh
  - .travis/after_success_static.sh
  - .travis/after_success_screenshots.sh
  - .travis/after_success_git.sh
  - .travis/after_success_deploy.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
