language: node_js
cache:
  directories:
    - node_modules
    - $HOME/.cache
    - $HOME/.yarn-cache
notifications:
  email: false
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/node_modules/slimerjs/src:$PATH
addons:
  firefox: "50.0"
node_js:
  - '6'
#before_install: .travis/before_install.sh
before_script:
  - sh -e /etc/init.d/xvfb start
  - yarn global add sassdoc http-server
sudo: required
script:
  - lerna exec --concurrency 1 -- yarn test
after_success:
#  - .travis/after_success_lint.sh
  - .travis/after_success_screenshots.sh
  - .travis/after_success_git.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
