name: Dataviz module auto publish

on:
  push:
    branches: [main, master]
    paths: packages/dataviz/**

jobs:
  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/dataviz

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org/'

      - name: Get package.json version
        id: current-version
        run: |
          localVersion="$(cat package.json | jq -r ".version")"
          echo "Local version is $localVersion"
          echo "::set-output name=current_version::$localVersion"

      - name: Check if package.json version is already published
        id: check-already-published
        run: |
          alreadyPublished="$(yarn info @talend/react-dataviz versions | sed -n "/'${{ steps.current-version.outputs.current_version }}'/ p" | wc -l)"
          echo "Is local version already published ? $alreadyPublished"
          echo "::set-output name=already-published::$alreadyPublished"

      - name: Install
        if: ${{ steps.check-already-published.outputs.already-published == 0 }}
        run: yarn install --frozen-lockfile

      - name: Test
        if: ${{ steps.check-already-published.outputs.already-published == 0 }}
        run: yarn test

      - name: Publish
        id: publish
        if: ${{ steps.check-already-published.outputs.already-published == 0 }}
        run: |
          yarn publish --non-interactive
          echo "::set-output name=published::done"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Update Talend CDN content
        id: cdn
        run: |
          curl -XPOST -u "frassinier:${{ secrets.PERSONAL_ACCESS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/talend/cdn-content/actions/workflows/download.yml/dispatches --data '{"ref": "main"}'

